# Generated by Django 3.0.7 on 2020-06-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200627_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='department',
        ),
    ]
